version: '3.8'
services:
  click-count:
    build: .
    ports:
      - '8080:8080'
    environment:
      REDIS_HOST: redis
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  redis_data:
