AWSTemplateFormatVersion: 2010-09-09
Description: Description of an EKS + Elasticache based environment
Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  KubernetesVersion:
    Type: String
    Description: Kubernetes Version
    Default: '1.21'
  Environment:
    Type: String
    Description: Environment

  # Network Parameters
  VPCCIDR:
    Type: String
    Description: CIDR block used to create the VPC (e.g. 10.0.0.0/24)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.0/24)
  PublicSubnet1CIDR:
    Type: String
    Description: CIDR block should used to create the public subnet in AZ1 (e.g. 10.0.0.0/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.0/26)
  PublicSubnet2CIDR:
    Type: String
    Description: CIDR block should used to create the public subnet in AZ2 (e.g. 10.0.0.64/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.64/26)
  PublicSubnet3CIDR:
    Type: String
    Description: CIDR block should used to create the public subnet in AZ3 (e.g. 10.0.0.64/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.64/26)
  PrivateSubnet1CIDR:
    Type: String
    Description: CIDR block should used to create the private subnet in AZ1 (e.g. 10.0.0.128/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.128/26)
  PrivateSubnet2CIDR:
    Type: String
    Description: CIDR block should used to create the private subnet in AZ2 (e.g. 10.0.0.192/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.192/26)
  PrivateSubnet3CIDR:
    Type: String
    Description: CIDR block should used to create the private subnet in AZ3 (e.g. 10.0.0.192/26)
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x. (e.g. 10.0.0.192/26)

  # Kubernetes staging cluster parameters
  MinSize:
    Type: Number
    Description: "minimum number of nodes in the cluster"
  DesiredSize:
    Type: Number
    Description: "the number of nodes the cluster is started with"
  MaxSize:
    Type: Number
    Description: "maximum number of nodes in the cluster"

Resources:
  Network:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'network/network.yml'
      Parameters:
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PublicSubnet3CIDR: !Ref PublicSubnet3CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        ApplicationName: !Ref ApplicationName
        Environment: !Ref Environment
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}/${Environment}/Network'
        - Key: Environment
          Value: !Ref Environment

  EksCluster:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'eks-cluster/eks-cluster.yml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        VpcId: !GetAtt Network.Outputs.VPC
        KubernetesVersion: !Ref KubernetesVersion
        SubnetIds: !GetAtt Network.Outputs.Subnets
        PublicSubnetIds: !GetAtt Network.Outputs.PublicSubnets
        Environment: !Ref Environment
        InstanceType: t3.small
        MinSize: !Ref MinSize
        DesiredSize: !Ref DesiredSize
        MaxSize: !Ref MaxSize
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}/${Environment}/EksCluster'
        - Key: Environment
          Value: !Ref Environment

  RedisCluster:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'redis-elasticache/redis-elasticache.yml'
      Parameters:
        ApplicationName: !Ref ApplicationName
        Environment: !Ref Environment
        VpcId: !GetAtt Network.Outputs.VPC
        SubnetIds: !GetAtt Network.Outputs.PrivateSubnets
        ApplicationSecurityGroupId: !GetAtt EksCluster.Outputs.ClusterSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}/${Environment}/RedisCluster'
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
