apiVersion: v1
kind: Service
metadata:
  labels:
    app: click-count
    app.kubernetes.io/managed-by: Helm
  name: click-count
  namespace: click-count
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: click-count
  type: LoadBalancer
