name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_fullname:
        required: true
        type: string
    secrets:
      application_name:
        required: true
      aws_account_id:
        required: true
      aws_region:
        required: true
      redis_host:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/github-oidc-role
          aws-region: ${{ secrets.aws_region }}
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name cluster-${{ secrets.application_name }}-${{ inputs.environment }} --region ${{ secrets.aws_region }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install release
        uses: hiberbee/github-action-helm@latest
        with:
          helm: upgrade -i click-count -n click-count --create-namespace deploy/helm-charts/click-count/ --set imageName=${{ inputs.image_fullname }} --set application.redisHost=${{ secrets.redis_host }}

